#!/usr/bin/env node
/* PVA Free Training -- Operations Desk data codec (Module 4 pilot)

   The shipped task data (module-4/desk-data.js) is encoded so answers and
   feedback can't be read in page source. Authors work on a plaintext source
   file with readable answer markers, then encode it.

   The plaintext source is NOT committed (it would publish the answers on
   GitHub and on the site). Recover it any time from the shipped file:

     node tools/desk-codec.js decode module-4/desk-data.js > m4-desk.src.json
     ...edit m4-desk.src.json...
     node tools/desk-codec.js encode m4-desk.src.json module-4/desk-data.js
     rm m4-desk.src.json            (*.src.json is git-ignored)

   Plaintext answer markers:
     findings[].correct: true          options[].correct: true
     triage rows[].answer: "<choiceId>"
     sequence correctOrder: ["id", ...]
     compose select fields[].accept: ["value", ...]
     compose multi  fields[].accept: [["a","b"], ["a"], ...]   (each an acceptable set)

   SALT / XOR_KEY / hash must match shared/workdesk.js. */

var fs = require("fs");
var SALT = "everfield-desk-v1";
var XOR_KEY = "EverfieldOpsDesk";

function h(str){
  var s = SALT + "|" + str;
  var x = 0x811c9dc5;
  for(var i = 0; i < s.length; i++){
    x ^= s.charCodeAt(i);
    x = Math.imul(x, 0x01000193) >>> 0;
  }
  return ("0000000" + x.toString(16)).slice(-8);
}
function xorBytes(buf){
  var out = Buffer.alloc(buf.length);
  for(var i = 0; i < buf.length; i++) out[i] = buf[i] ^ XOR_KEY.charCodeAt(i % XOR_KEY.length);
  return out;
}

function lockStage(st){
  if(st.type === "decision"){
    (st.findings || []).forEach(function(f){ f.k = h(st.id + "|f|" + f.id + "|" + (f.correct ? 1 : 0)); delete f.correct; });
    (st.options || []).forEach(function(o){ o.k = h(st.id + "|o|" + o.id + "|" + (o.correct ? 1 : 0)); delete o.correct; });
  }
  if(st.type === "triage"){
    st.rows.forEach(function(r){
      if(!r.answer) throw new Error("triage row without answer: " + st.id + "/" + r.id);
      r.k = h(st.id + "|row|" + r.id + "|" + r.answer); delete r.answer;
    });
  }
  if(st.type === "sequence"){
    st.items.forEach(function(it){ it.k = [h(st.id + "|seq|" + it.id + "|" + st.correctOrder.indexOf(it.id))]; });
    delete st.correctOrder;
  }
  if(st.type === "compose"){
    st.fields.forEach(function(f){
      if(f.type === "select"){ f.acc = f.accept.map(function(v){ return h(st.id + "|fld|" + f.id + "|" + v); }); delete f.accept; }
      if(f.type === "multi"){ f.acc = f.accept.map(function(set){ return h(st.id + "|fld|" + f.id + "|" + set.slice().sort().join(",")); }); delete f.accept; }
    });
  }
}
function unlockStage(st){
  if(st.type === "decision"){
    (st.findings || []).forEach(function(f){ f.correct = f.k === h(st.id + "|f|" + f.id + "|1"); delete f.k; });
    (st.options || []).forEach(function(o){ o.correct = o.k === h(st.id + "|o|" + o.id + "|1"); delete o.k; });
  }
  if(st.type === "triage"){
    st.rows.forEach(function(r){
      r.answer = st.choices.map(function(c){ return c.id; }).filter(function(c){ return r.k === h(st.id + "|row|" + r.id + "|" + c); })[0];
      delete r.k;
    });
  }
  if(st.type === "sequence"){
    var order = [];
    st.items.forEach(function(it){
      for(var p = 0; p < st.items.length; p++){ if(it.k.indexOf(h(st.id + "|seq|" + it.id + "|" + p)) !== -1) order[p] = it.id; }
      delete it.k;
    });
    st.correctOrder = order;
  }
  if(st.type === "compose"){
    st.fields.forEach(function(f){
      if(f.type === "select"){ f.accept = f.options.map(function(o){ return o.value; }).filter(function(v){ return f.acc.indexOf(h(st.id + "|fld|" + f.id + "|" + v)) !== -1; }); delete f.acc; }
      if(f.type === "multi"){
        var vals = f.options.map(function(o){ return o.value; }), sets = [];
        for(var m = 0; m < (1 << vals.length); m++){
          var set = vals.filter(function(_, i){ return m & (1 << i); });
          if(f.acc.indexOf(h(st.id + "|fld|" + f.id + "|" + set.slice().sort().join(","))) !== -1) sets.push(set);
        }
        f.accept = sets; delete f.acc;
      }
    });
  }
}

function encode(src, out){
  var data = JSON.parse(fs.readFileSync(src, "utf8"));
  data.tasks.forEach(function(t){ t.stages.forEach(lockStage); });
  var b64 = xorBytes(Buffer.from(JSON.stringify(data), "utf8")).toString("base64");
  var body = "/* Module 4 Operations Desk task data -- generated by tools/desk-codec.js. Do not edit by hand. */\n" +
             "window.M4_DESK_DATA = \"" + b64 + "\";\n";
  fs.writeFileSync(out, body);
  console.error("encoded " + data.tasks.length + " tasks -> " + out + " (" + body.length + " bytes)");
}
function decode(file){
  var txt = fs.readFileSync(file, "utf8");
  var m = txt.match(/M4_DESK_DATA = "([^"]+)"/);
  var data = JSON.parse(xorBytes(Buffer.from(m[1], "base64")).toString("utf8"));
  data.tasks.forEach(function(t){ t.stages.forEach(unlockStage); });
  process.stdout.write(JSON.stringify(data, null, 2) + "\n");
}

var cmd = process.argv[2];
if(cmd === "encode") encode(process.argv[3], process.argv[4]);
else if(cmd === "decode") decode(process.argv[3]);
else { console.error("usage: desk-codec.js encode <src.json> <out.js> | decode <desk-data.js>"); process.exit(1); }
